### ISSUE TITLE
[Bug/Incompatibility] Crashes on Minecraft 1.16.2.

### ISSUE THREAD

**Issue by YTG1234** [CafeteriaGuild/FallFlyingLib#1]
Log: https://paste.ee/p/FQV91
**All info you need is probably in the log, but:**
* Java Version: 8
* OS: macOS 10.14.6

**Comment by YTG1234** [comment]
@adriantodt

**Comment by YTG1234** [comment]
@adriantodt

**Comment by YTG1234** [comment]
Looks like you didn't specify a boolean type, but I looked at the code and you did. Very weird

**Comment by NotJustAnna** [comment]
Busy atm, will investigate later

**Comment by NotJustAnna** [comment]
I need to ask you to do add `-Dmixin.debug=true` as a JVM property and give me this new log.

**Comment by YTG1234** [comment]
@adriantodt https://paste.ee/p/DtuvR

**Comment by YTG1234** [comment]
This must be an incompatibility since it works with other mods. Now to find the causing mod.

**Comment by YTG1234** [comment]
@adriantodt Found the incompatible mod: Elytra Hopping
