### ISSUE TITLE
Warn Log 'server networking not settup yet'

### ISSUE THREAD

**Issue by milkev** [CafeteriaGuild/FallFlyingLib#10]
when a player joins a world (in single player or on a dedicated server), a rather concerning error message pops up in the log. Though this doesnt seem to have any impact to anything in game or cause any problems. This warn log is always just before `x player joined the game`

Dev Environment (intellij);
```
[10:07:27] [Server thread/WARN] (FallFlyingAbilityTracker) 
Player ServerPlayerEntity['Player342'/381, l='ServerLevel[New World]', x=135.50, y=67.00, z=-47.50] could not be synced because server networking isn't set up yet.
```

Client/Singleplayer;
```
 '10:14:10.071
net.adriantodt.fallflyinglib.impl.FallFlyingAbilityTracker
Server thread
Player class_3222['milkev'/228, l='ServerLevel[New World]', x=58.50, y=68.00, z=-153.50] could not be synced because server networking isn't set up yet.'
```

Dedicated Server;
```
[08:54:15] [Server thread/WARN]: 
Player class_3222['milkev'/220, l='ServerLevel[world]', x=-129.50, y=67.00, z=70.50] could not be synced because server networking isn't set up yet.
```

Seems to be caused by [player.networkHandler](https://github.com/CafeteriaGuild/FallFlyingLib/blob/master/src/main/java/net/adriantodt/fallflyinglib/impl/FallFlyingAbilityTracker.java#L47) returning null. Perhaps because PAL is calling sync to early?

the player has no uuid at the point at which the warn is called. using `player.getServerWorld().getPlayerByUuid(player.getUuid())` in place of `player.networkHandler` seems to result in the same thing.

if you feel full logs would help diagnose this issue, i can send them, however i do not believe they will help with this.

Unless this is found to actually cause any issues, i believe its best to just remove the warn log entirely, if only to ease the mind of any player or server owner finding this in their logs.

**Comment by NotJustAnna** [comment]
FallFlyingLib will (hopefully) be superseded by an official Fabric API module: https://github.com/FabricMC/fabric/pull/1815

**Comment by NotJustAnna** [comment]
FallFlyingLib was superseded by the official Elytra events available at Fabric Entity API.
