### ISSUE TITLE
Incompatible with Mods that need to change the behavior of `tickFallFlying`

### ISSUE THREAD

**Issue by quiqueck** [CafeteriaGuild/FallFlyingLib#12]
I am working on BetterEnd. We tried to fix compat issues with the Origin Mod, and just noticed that FallFlyingLib is using a `@Redirect` to apply custom changes to `tickFallFlying`.
https://github.com/CafeteriaGuild/FallFlyingLib/blob/b281b4835bda707efea3f451e0fa1d727a86f126/src/main/java/net/adriantodt/fallflyinglib/mixin/LivingEntityMixin.java#L25-L31

This makes the library incompatible with any other Mod that modifies the behaviour of `tickFallFlying`. I had a look at the Code, and it should be easily replaceable with a canceling `HEAD`-inject to `tickFallFlying`. Would you please consider to change the Mixin? That would make the Lib much more compatible.

**Comment by NotJustAnna** [comment]
_Honestly, I'd prefer to kill FFL from existance._

Mistakes were made regarding my choices with FFL, and I started creating a better version of FFL, this time with the ultimate goal to PR all the code to Fabric API. Sadly, I don't have enough time to finish it.

https://github.com/CafeteriaGuild/elytra-pipeline

I'd much more prefer to have a better, Fabric API-native way to handle all of this, and to axe down FFL from existance.

**Comment by NotJustAnna** [comment]
FallFlyingLib will (hopefully) be superseded by an official Fabric API module: https://github.com/FabricMC/fabric/pull/1815

**Comment by NotJustAnna** [comment]
FallFlyingLib was superseded by the official Elytra events available at Fabric Entity API.
