### ISSUE TITLE
1.17 beta is incompatible with Identity

### ISSUE THREAD

**Issue by apace100** [CafeteriaGuild/FallFlyingLib#9]
Hi! I use the beta version of FFL in my mod (version _3.0.0-beta.2_ to be exact), and one of the users reported my mod being incompatible with Identity (https://github.com/Draylar/identity). I tracked it down to being a crash that occurs on startup when both FallFlyingLib and Identity are installed.

The issue seems to be that both Identity and FFL use an `EntityAccessor` mixin with an accessor to the `setFlag` method. I'm not sure how to handle these conflicts myself, otherwise I would've PR'd, so I hope you know how to proceed (probably some `@Unique` stuff?).

Here's Identity's `EntityAccessor` mixin: https://github.com/Draylar/identity/blob/1.17/src/main/java/draylar/identity/mixin/EntityAccessor.java

I attached the error of the crash if you need it: [identitycrash.log](https://github.com/CafeteriaGuild/FallFlyingLib/files/6688410/identitycrash.log)

And lastly, here's a link to the original issue on my mod: https://github.com/apace100/origins-fabric/issues/354

Thanks!

**Comment by NotJustAnna** [comment]
FallFlyingLib will (hopefully) be superseded by an official Fabric API module: https://github.com/FabricMC/fabric/pull/1815

**Comment by NotJustAnna** [comment]
FallFlyingLib was superseded by the official Elytra events available at Fabric Entity API.
